# pubspec.yaml — INDENT-SAFE (2 spaces, no tabs)
# • Adds both assets/images/ and assets/icons/ folders for asset bundling.
# • Keeps your forked crystal_navigation_bar as a local path dependency.
# • glass_nav_bar, InterSemiBold, and MyIconFont entries are intact.

name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.8.0-278.1.beta'

# ─── Dependencies ────────────────────
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Forked crystal_navigation_bar with widget-based icon/title support.
  crystal_navigation_bar:
    path: ./crystal_navigation_bar          # ← adjust relative path


  vibration: ^3.1.3
  glassmorphism: ^3.0.0
  photo_manager: ^3.7.1

# ─── Dev-dependencies ───────────────
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ─── Flutter section ────────────────
flutter:
  uses-material-design: true

  fonts:
    - family: InterSemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf